version: "3.8"
services:
  dockeeper:
    image: ghcr.io/onflux-tech/dockeeper:latest
    environment:
      - CLEANUP_INTERVAL_HOURS=24 # Interval to clean up old logs
      - NOTIFICATION_SERVICE= # wuzapi or evolution
      # Evolution_url = https://your-domain-evolution-api/message/sendText/your-instance
      # Wuzapi_url = https://your-domain-wuzapi-api/chat/send/text
      - NOTIFICATION_URL=
      # Evolution_key = 111111111111-1111-1111-111111111111
      # Wuzapi_key = 1234ABCD
      - NOTIFICATION_KEY=
      - NOTIFICATION_NUMBER= # 5511999999999
      # DOCKER_MODE=staandalone -> container1;container2;container3
      # DOCKER_MODE=swarm -> service_service1;service_service2;service_service3
      - HEALTH_CHECKS=
      - DOCKER_MODE= # standalone or swarm
      - PORT=5000 # Port to run the application
      - VOLUME_RETENTION_DAYS=7 # Number of days to keep unused volumes. Set to 0 to disable cleanup or remove the variable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - your-network
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=your-network"
        - "traefik.http.routers.dockeeper.rule=Host(`dockeeper.yourdomain.com.br`)"
        - "traefik.http.routers.dockeeper.entrypoints=websecure"
        - "traefik.http.routers.dockeeper.priority=1"
        - "traefik.http.routers.dockeeper.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.dockeeper.service=dockeeper"
        - "traefik.http.services.dockeeper.loadbalancer.server.port=5000"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

networks:
  your-network:
    external: true
    name: your-network
